### ISSUE TITLE
Domain roles are not created

### ISSUE THREAD

**Issue by darrylweaver** [VerneGlobal/ansible-role-os-projects#1]
When adding a new domain role, it is not created automatically, only project roles are.

**Comment by autonomouse** [comment]
At risk of stating the obvious, this prevents fully automated setup of the candidate (and other) environments

**Comment by darrylweaver** [comment]
#

**Comment by darrylweaver** [comment]
Fix committed #2

**Comment by darrylweaver** [comment]
We have now got an updated stackhpc/ansible-role-os-projects repo, which now deploys domains correctly, so this repo is superseded.
